# Hands on Data Preprocessing First in Python

### By Johannes Simatupang M.Kom.,COBIT5 (Feb 2026)

COMP6577 - Machine Learning >>> Bina Nusantara University

In [1]:
#load library
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
#Importing the Dataset
dataset = pd.read_csv("https://raw.githubusercontent.com/joh4nnes/MLData/main/purchase.csv", encoding='latin-1')

In [2]:
print(dataset.head())

       States   Age   Salary Purchased
0       Texas  44.0  72000.0        No
1     Florida  27.0  48000.0       Yes
2  California  30.0  54000.0        No
3       Texas  38.0  61000.0        No
4  California   NaN  65000.0       Yes


### X = independent variables and y = dependent variable

In [ ]:
X = dataset.iloc[1, [0,1,2]].values
y = dataset.iloc[:, 3].values 

In [4]:
# Print Independent Variables
print("X:")
print(X)

X:
[['Texas' 44.0 72000.0]
 ['Florida' 27.0 48000.0]
 ['California' 30.0 54000.0]
 ['Texas' 38.0 61000.0]
 ['California' nan 65000.0]
 ['Texas' 35.0 58000.0]
 ['California' 40.0 nan]
 ['Texas' 48.0 79000.0]
 ['Florida' 50.0 83000.0]
 ['Texas' 37.0 67000.0]]


In [5]:
# Print Dependent Variables
print("Y:")
print(y)

Y:
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Handling the missing values

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [7]:
X

array([['Texas', 44.0, 72000.0],
       ['Florida', 27.0, 48000.0],
       ['California', 30.0, 54000.0],
       ['Texas', 38.0, 61000.0],
       ['California', 38.77777777777778, 65000.0],
       ['Texas', 35.0, 58000.0],
       ['California', 40.0, 65222.22222222222],
       ['Texas', 48.0, 79000.0],
       ['Florida', 50.0, 83000.0],
       ['Texas', 37.0, 67000.0]], dtype=object)

### Encoding the categorical variables

In [8]:
#Encoding the categorical variables
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y = y.reshape(-1, 1)

In [9]:
print(y)

[[0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]]


### Creating dummy variables for the encoded categorical values

In [10]:
#Creating dummy variables for the encoded categorical values
transformer = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [0])],remainder='passthrough')
X = np.array(transformer.fit_transform(X), dtype=np.float64)

In [11]:
X

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.87777778e+01,
        6.50000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.52222222e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

### Splitting the datasets

In [12]:
#Splitting the datasets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0 )

### Feature Scaling

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

In [14]:
X_train

array([[ 1.73205081, -0.37796447, -1.29099445,  0.05261351,  0.06895002],
       [-0.57735027, -0.37796447,  0.77459667, -0.25350148,  0.29985242],
       [-0.57735027,  2.64575131, -1.29099445, -1.97539832, -1.89372037],
       [ 1.73205081, -0.37796447, -1.29099445,  0.26306757,  0.09460584],
       [-0.57735027, -0.37796447,  0.77459667,  1.64058505,  1.68526682],
       [-0.57735027, -0.37796447,  0.77459667, -0.0813118 , -0.39285478],
       [-0.57735027, -0.37796447,  0.77459667,  0.95182631,  0.87710842],
       [-0.57735027, -0.37796447,  0.77459667, -0.59788085, -0.73920837]])

In [15]:
y_train

array([[ 0.77459667],
       [ 0.77459667],
       [ 0.77459667],
       [-1.29099445],
       [ 0.77459667],
       [-1.29099445],
       [-1.29099445],
       [ 0.77459667]])

In [16]:
X_test

array([[ 1.73205081, -0.37796447, -1.29099445, -1.45882927, -1.20101317],
       [-0.57735027,  2.64575131, -1.29099445,  1.98496442,  2.14707161]])

source : https://www.aionlinecourse.com/tutorial/machine-learning/data-preprocessing